version: '3.8'

services:
  # mongo_db:
  #   image: mongo
  #   container_name: mongo_db
  #   environment:
  #     MONGO_INITDB_DATABASE: traffic_detection
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #   ports:
  #     - "27017:27017" # Default MongoDB port
  #   networks: 
  #     - traffic-ai-detection-network
  #   healthcheck:
  #     test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 10s
  
  ai-traffic-api:
    container_name: ai-traffic-api
    build:
      context: .
      dockerfile: Dockerfile
    #command: bash -c "uvicorn api:app --host 0.0.0.0 --port 80 --reload" # Adjust this command as necessary
    ports:
      - "8001:8000"
    # depends_on:
    #   - mongo_db
    environment:
      DATABASE_URL: mongodb://km2401:km2401@tuanhoangdinh.ddns.net:27017/example_db # MongoDB connection string
      DATABASE_NAME: example_db
      # DATABASE_URL: mongodb://mongo_db:27017/traffic_detection # MongoDB connection string
    # networks: 
    #   - traffic-ai-detection-network

  mongo-express-server:
    container_name: MongoExpress
    image: mongo-express
    environment:
      # - ME_CONFIG_MONGODB_SERVER=mongo_db
      # - ME_CONFIG_MONGODB_PORT=27019
      ME_CONFIG_MONGODB_URL: "mongodb://km2401:km2401@tuanhoangdinh.ddns.net:27017/example_db"
      # ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo_db:27017
      # - ME_CONFIG_BASICAUTH_USERNAME=admin
      # - ME_CONFIG_BASICAUTH_PASSWORD=admin
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    ports:
      - "8082:8081" # Access Mongo Express on port 8081
    # networks:
    #   - traffic-ai-detection-network
    # depends_on:
    #   mongo_db:
    #     condition: service_healthy

# Optionally, you can include volumes for MongoDB data persistence
# volumes:
#   ai-traffic_data:
#     driver: local

networks:
  traffic-ai-detection-network:
    driver: bridge